.Dd February 18, 2000
.Dt diary 1
.Os Linux
.Sh NAME
.Nm diary
.Nd a text-based diary.
.Sh SYNOPSIS
.Nm diary

.Nm diary
entry <text to insert into diary>

.Nm diary
cat [<date string>]
.Nm diary
view [<date string>]

.Nm diary
edit [<date string>]

.Nm diary
list [<number of entries>]
.Nm diary
<month name> [year]
.Nm diary
review [<number of days>]

.Nm diary
grep <search string>
.Nm diary
search <search string>

.Sh DESCRIPTION
.Ar Diary
is a simple yet effective daily diary.  It allows daily entries to be stored,
searched and reviewed in a variety of ways.  Diary content is manipulated with
a text editor (the default is
.Ar vi
) and stored in simple text "pages", one for each day.
.Pp
.Ar Diary
owes much of its functionality to various standard shell utilities,
particularly
.Ar date
(1) and
.Ar grep
(1).  Date specifications like "yesterday", "3 days ago" or "last week" work
because they are interpreted directly by
.Ar date
(1).  Similarly any options supported by
.Ar grep
(1) may be added to the
.Ar grep
and
.Ar search
subcommands.
.Pp
Non-editable pages are opened with
.Ar less
(1).  When a number of pages are returned by the
.Ar search
subcommand they can be cycled through using the "u" and "i"
keys.  Why? because they don't conflict with existing
.Ar less
(1) commands and
are easier to reach then the standard file cycling keys.
.Sh EXAMPLES
The easiest way to see how
.Ar diary
works is through a series of examples.
.Pp

.Bl -tag -width Ds
.It Cm diary
Open today's page for editing.
.It Cm diary entry Hello World
Add the line "Hello World" to today's diary page.

.It Cm diary cat
Dump today's page to stdout.
.It Cm diary cat last monday
Dump last Monday's page to stdout.

.It Cm diary view
View today's page.
.It Cm diary view 10/15/99
Open october 15, 1999 page for viewing.
.It Cm diary view 2 days ago
View the day before yesterday's page.

.It Cm diary edit yesterday
This is cheating! ... but you can edit
past entries if you really want to.

.It Cm diary list 5
Output the last 5 non-blank pages.
.It Cm diary october
Output all of the past October's non-blank pages.
.It Cm diary october 2000
Output all of year 2000 October's non-blank pages.

.It Cm diary review
Output entries for the last week.
.It Cm diary review 3
Output entries for the last 3 calendar days.

.It Cm diary grep [Ff]ind
Grep pages for lines containing find or Find.
.It Cm diary grep -F Find
Search for fixed string (options are passed directly to grep).
.It Cm diary search "^Fixed"
Open pages for viewing that contain lines that start with "Fixed".
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev EDITOR
If set will be used instead of the default, /usr/bin/vim.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa $HOME/.diary
Contains all configuration, temporary and data files for the
.Ar diary
program.
.It Pa $HOME/.diary/diaryrc
This file gets included at runtime and can be used to override standard configuration
variables.
.It Pa $HOME/.diary/pages
The directory that holds the actual diary page data.
.Sh SEE ALSO
date(1), grep(1), less(1)
